* Debugging
Adiciona bloco de /debugging/ para meu init.el

#+begin_src elisp

(if init-file-debug
      (setq use-package-verbose t
            use-package-expand-minimally nil
            use-package-compute-statistics t
            debug-on-error t)
    (setq use-package-verbose nil
          use-package-expand-minimally t))
  
#+end_src

#+RESULTS:
: t



* Pacotes

** Inicialização de Pacotes

#+begin_src elisp :results none 
  (require 'package)
    
    (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))


  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** Rainbow Delimiters
Pintam os parênteses para ficar mais fácil de acompanhar.
#+begin_src elisp :results none 
    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Evil
Vamos usar a movimentação do Vim.

#+begin_src elisp :results none

            (use-package evil
              :init
              (setq evil-want-integration t)
              (setq evil-want-keybinding nil)
              (setq evil-want-C-u-scroll t)
      	(setq evil-want-C-i-jump nil)
    	:config
  	(evil-mode 1)
  (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
  (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

  (evil-set-initial-state 'messages-buffer-mode 'normal)
  (evil-set-initial-state 'dashboard-mode 'normal)
  )
              

#+end_src

*** Evil Collection

Ajuda a deifnir atalhos do tipo Evil.

#+begin_src emacs-lisp :results none
  (use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
#+end_src


** General
Pacote para configurar mais facilmente /keybindings/.

#+begin_src elisp :results none
  (use-package general
           :config
            (general-evil-setup t)
        	(general-create-definer rune/leader-keys
     				:keymaps '(normal insert visual emacs)
      				:prefix "SPC"
     				:global-prefix "C-SPC"))

#+end_src

** Which Key
Nos dá o menu da árvore de comandos, acessível com qual atalho

#+begin_src elisp :results none

  (use-package which-key
  :defer 0
  :diminish which-key-mode
  :config
  (which-key-mode)
  (setq which-key-idle-delay 1))

#+end_src

** Doom Modeline

Lembre-se de rodar o comando _M-x all-the-icons-install-fonts_ para fazer tudo funcionar legal.

#+begin_src elisp :results none
  (use-package all-the-icons)

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))
#+end_src

** Ivy

Sistema muito robusto para completar comandos.

#+begin_src elisp :results none
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
    :map ivy-minibuffer-map
        ("TAB". ivy-alt-done)
        ("C-l" . ivy-alt-done)
        ("C-j" . ivy-next-line)
        ("C-k" . ivy-previous-line)
     :map ivy-switch-buffer-map
        ("C-k" . ivy-precious-line)
        ("C-l" . ivy-done)
        ("C-d" . ivy-switch-buffer-kill)
     :map ivy-reverse-i-search-map
  	("C-k" . ivy-previous-line)
  	("C-d" . ivy-reverse-i-search-kill))
     :config
     (ivy-mode 1)
     )
#+end_src

*** Ivy Rich

Complementa como o ivy se comporta com o counsel.

#+begin_src elisp :results none
        (use-package ivy-rich
          :after ivy
          :init
  	(ivy-rich-mode 1))
#+end_src

** Counsel

Mais um /framework/ de completar comandos. Essencial para termos funcionalidade mais complicada.

#+begin_src elisp :results none
  (use-package counsel
  :bind (("C-M-j" . 'counsel-switch-buffer)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))
  :custom
  (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
  :config
  (counsel-mode 1))
#+end_src
    
** Dired

O melhor explorador de arquivos disponível.

#+begin_src emacs-lisp :results none
  (use-package dired
  :ensure nil
  :commands (dired dired-jump)
  :bind (("C-x C-j" . dired-jump))
  :custom ((dired-listing-switches "-agho --group-directories-first"))
  :config
  (evil-collection-define-key 'normal 'dired-mode-map
    "h" 'dired-single-up-directory
    "l" 'dired-single-buffer))

(use-package all-the-icons-dired
  :hook (dired-mode . all-the-icons-dired-mode))

(use-package dired-open
  :commands (dired dired-jump)
  :config
  ;; Doesn't work as expected!
  ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
  (setq dired-open-extensions '(("png" . "feh")
                                ("mkv" . "mpv"))))

(use-package dired-hide-dotfiles
  :hook (dired-mode . dired-hide-dotfiles-mode)
  :config
  (evil-collection-define-key 'normal 'dired-mode-map
    "H" 'dired-hide-dotfiles-mode))
#+end_src


* Configuração Inicial

** Mensagem de início
Inibe a mensagem de início
#+begin_src elisp :results none
  (setq inhibit-startup-message t)
#+end_src

** Sino Visual
Inicia sino visual

#+begin_src elisp :results none
  (setq visible-bell t)
#+end_src

** Elementos de UI
Desliga elementos da interface de usuário, para
um /look/ mais /clean/.

#+begin_src elisp :results none
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

*** Números das linhas
Liga o número das linhas em tudo, exceto alguns modos.
#+begin_src elisp :results none
    (global-display-line-numbers-mode t)

    (column-number-mode)
    (dolist (mode '(org-mode-hook
    		term-mode-hook
    		eshell-mode-hook))
      (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src


** ESC para Sair

Configura o botão de ESC para servir como C-g

#+begin_src elisp :results none
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src


* Configuração visual
Para todas as questões que vão além da UI básica, mas sim
cores e temas, fontes e etc.
** Tema
Um tema simples para tudo
#+begin_src elisp :results none
  (load-theme 'modus-vivendi t)
#+end_src

